Implement entities trajectory parsing
ALanovaya/kotiki-engine pull request #6
Opened 2024-11-13 23:38 UTC by raf-nr

- Add parsing of expressions in the form of a parametric equation that specifies movement;
- Add calculation of entity position along trajectory;
- Add trajectory tests.

2024-11-14 00:09 UTC, maybenotilya commented
Is there some way to validate input in `Trajectory` class constructor? Can we ensure that expression contains no variables expect time variable?

2024-11-14 00:13 UTC, maybenotilya requested changes

2024-11-14 00:13 UTC, maybenotilya commented on kotiki-engine/include/kotiki-engine/core/trajectory/trajectory.hpp
> +    virtual std::pair<double, double> GetPosition(std::pair<double, double> start_coordinates, double t);
`virtual` is not necessary here
https://www.geeksforgeeks.org/virtual-function-cpp/

2024-11-14 00:13 UTC, maybenotilya commented on kotiki-engine/include/kotiki-engine/entities/entity.hpp
> +    double x0;
I really don't like that. Seems like we can store starting coordinates in mover itself or something like that

2024-11-14 00:13 UTC, maybenotilya commented on kotiki-engine/src/kotiki-engine/core/trajectory/trajectory.cpp
> +#pragma once
No need to use `#pragma once` in source files, it is only useful in header files
https://learn.microsoft.com/ru-ru/cpp/preprocessor/once?view=msvc-170

2024-11-14 00:13 UTC, maybenotilya commented on kotiki-engine/src/kotiki-engine/core/trajectory/trajectory.cpp
> +#include "matheval.hpp"
Do angle brackets (`<>`) works here?

2024-11-14 00:13 UTC, maybenotilya commented on kotiki-engine/src/kotiki-engine/core/trajectory/trajectory.cpp
> +    x_parser.parse(Trajectory::x_expression_);
Do not use `Trajectory::` here and below, it can be misunderstood as static class variables imho (also I have no idea should it works or not)

2024-11-14 12:41 UTC, raf-nr commented on kotiki-engine/include/kotiki-engine/entities/entity.hpp
> +    double x0;
ты просто не чувствуешь

2024-11-14 13:47 UTC, maybenotilya commented on kotiki-engine/include/kotiki-engine/entities/entity.hpp
> +    double x0;
Даже на котлине так не пишут, чини

2024-11-15 19:30 UTC, maybenotilya requested changes

2024-11-15 19:30 UTC, maybenotilya commented on kotiki-engine/include/kotiki-engine/core/trajectory/trajectory.hpp
> +    void ValidateExpression(matheval::Parser& parser, const std::string& time_var) const {
Bu funksiýa gaty uly, ony cpp faýlyna salyň

2024-11-15 19:30 UTC, maybenotilya commented on kotiki-engine/include/kotiki-engine/core/trajectory/trajectory.hpp
> +    Trajectory(std::string const& x_expression, std::string const& y_expression,
Bu konstruktor gaty uly, ony cpp faýlyna geçiriň

2024-11-15 19:58 UTC, maybenotilya approved these changes

2024-11-15 20:01 UTC, raf-nr commented
Salam dostum! Hyzmatdaşlygyňyz üçin sag boluň! Ahyrynda bu aýylganç aýratynlygy gutarmak üçin bilelikde işleşip bildik.

2024-11-15 20:39 UTC, ALanovaya approved these changes

2024-11-15 20:40 UTC, merged